using System.Collections.Generic;

public static class NodeSessionMap
{
    private static readonly Dictionary<string, string> map = new Dictionary<string, string>
    {
        { "Session2", "Session2" },
        { "Session2TranslationReview", "Session2" },
        { "Session2ReviewToru", "Session2" },
        { "Session2ReviewHodi", "Session2" },
        { "Session2ReviewDah", "Session2" },
        { "Session2Signal", "Session2" },
        { "SurfaceMessage", "Session2" },
        { "SurfaceQuestions", "Session2" },
        { "SurfaceWordEvidence", "Session2" },
        { "UzimaContextCheck", "Session2" },
        { "KamenContextCheck", "Session2" },
        { "MoranContext", "Session2" },
        { "PadaContextCheck", "Session2" },
        { "MoranRefinementS2", "Session2" },
        { "CooperationMessage", "Session2" },
        { "RukaContextCheck", "Session2" },
        { "VornContextS2", "Session2" },
        { "ReportDecision", "Session2" },
        { "MarenFullReport", "Session2" },
        { "MarenSoftReport", "Session2" },
        { "MarenHiddenReport", "Session2" },
        { "MarenUncertainReport", "Session2" },
        { "MarenInvestigation", "Session2" },
        { "MarenSecondQuestion", "Session2" },
        { "ResearchDecision", "Session2" },
        { "ResearchHub", "Session2" },
        { "ResearchArchive", "Session2" },
        { "ResearchVorn", "Session2" },
        { "ResearchExtraction", "Session2" },
        { "ResearchTransmissions", "Session2" },
        { "Session2Ending", "Session2" },
        { "Session3", "Session3" },
        { "Session3Ask27", "Session3" },
        { "Session3AskFragment", "Session3" },
        { "Session3AskPreviousVorn", "Session3" },
        { "Session3AskKaelVorn", "Session3" },
        { "Session3NeutralContact", "Session3" },
        { "Session3VornRefinement", "Session3" },
        { "Session3VornFinalCheck", "Session3" },
        { "Session3AfterVornCheck", "Session3" },
        { "Session3Utisa", "Session3" },
        { "Session3MarenOpening", "Session3" },
        { "Session3MarenContact", "Session3" },
        { "Session3MarenUtisaReaction", "Session3" },
        { "Session3MarenEvidencePressure", "Session3" },
        { "Session3NoMarenVersion", "Session3" },
        { "Session3InterpretationChoice", "Session3" },
        { "Session3ResearchStart", "Session3" },
        { "Session3ResearchHub", "Session3" },
        { "ResearchVornIdentityS3", "Session3" },
        { "ResearchIncidentS3", "Session3" },
        { "ResearchVProgramS3", "Session3" },
        { "ResearchOldTransmissionS3", "Session3" },
        { "Session3AfterResearch", "Session3" },
        { "Session3FinalContact", "Session3" },
        { "Session3Ending", "Session3" },
        { "Session4_Start", "Session4_Start" },
        { "Session4_ResearchHub", "Session4_Start" },
        { "Session4_ResearchTech", "Session4_Start" },
        { "Session4_ResearchCoordinates", "Session4_Start" },
        { "Session4_ResearchHistory", "Session4_Start" },
        { "Session4_ResearchV27", "Session4_Start" },
        { "Session4_MarenBriefing", "Session4_Start" },
        { "Session4_DhornContact", "Session4_Start" },
        { "Session4_DhornQuestions", "Session4_Start" },
        { "Session4_ReportToMaren", "Session4_Start" },
        { "Session4_Phase2Update", "Session4_Start" },
        { "Session4_Ending", "Session4_Start" },
        { "Session4_TimeSkip", "Session4_Start" },
        { "Session5_Start", "Session5_Start" },
        { "Session5_CrisisCheck", "Session5_Start" },
        { "Session5_CheckVibrations", "Session5_Start" },
        { "Session5_CheckCommand", "Session5_Start" },
        { "Session5_CheckSignal", "Session5_Start" },
        { "Session5_DhornRequest", "Session5_Start" },
        { "Session5_MarenRequest", "Session5_Start" },
        { "Session5_InterpretationCrisis", "Session5_Start" },
        { "Session5_ChoiceSetup", "Session5_Start" },
        { "Session5_MajorChoice", "Session5_Start" },
        { "Session5_DhornRouteEnd", "Session5_Start" },
        { "Session5_GovernmentRouteEnd", "Session5_Start" },
        { "Session5_IndependentRouteEnd", "Session5_Start" },
        { "Session6_Start", "Session6_Start" },
        { "Session6_DhornRoute", "Session6_Start" },
        { "Session6_GovernmentRoute", "Session6_Start" },
        { "Session6_IndependentRoute", "Session6_Start" },
        { "Session6_IndependentHub", "Session6_Start" },
        { "Session6_ResearchV27Technical", "Session6_Start" },
        { "Session6_ResearchMarks", "Session6_Start" },
        { "Session6_ResearchPrivateSignal", "Session6_Start" },
        { "Session6_ResearchSector", "Session6_Start" },
        { "Session6_IndependentAfterResearch", "Session6_Start" },
        { "Session6_CommonSymbol", "Session6_Start" },
        { "Session6_Ending", "Session6_Start" },
        { "Session7_Start", "Session7_Start" },
        { "Session7_BoxHub", "Session7_Start" },
        { "Session7_Photo", "Session7_Start" },
        { "Session7_Notebook", "Session7_Start" },
        { "Session7_Transmitter", "Session7_Start" },
        { "Session7_Letter", "Session7_Start" },
        { "Session7_AssembleTruth", "Session7_Start" },
        { "Session7_MarenCall", "Session7_Start" },
        { "Session7_DhornContact", "Session7_Start" },
        { "Session7_FinalMediation", "Session7_Start" },
        { "Session7_TruthCheck", "Session7_Start" },
        { "Session7_FinalChoiceTruth", "Session7_Start" },
        { "Session7_FinalChoiceNormal", "Session7_Start" },
        { "Session7_TruthChoice", "Session7_Start" },
        { "Session7_GovernmentChoice", "Session7_Start" },
        { "Session7_DhornChoice", "Session7_Start" },
        { "Session7_Ending", "Session7_Start" },
        { "Session8_Start", "Session8_Start" },
        { "Session8_EndingRouter", "Session8_Start" },
        { "Session8_DhornEnding", "Session8_Start" },
        { "Session8_DhornEpilogue", "Session8_Start" },
        { "Session8_GovernmentEnding", "Session8_Start" },
        { "Session8_GovernmentEpilogue", "Session8_Start" },
        { "Session8_TruthEnding", "Session8_Start" },
        { "Session8_TruthEpilogue", "Session8_Start" },
        { "Session8_WarEnding", "Session8_Start" },
        { "Session8_WarEpilogue", "Session8_Start" },
        { "Session8_End", "Session8_Start" },
    };

    public static string GetSessionFor(string nodeName)
    {
        if (string.IsNullOrEmpty(nodeName))
            return null;

        return map.TryGetValue(nodeName, out string session) ? session : null;
    }
}
